### ISSUE TITLE
importlib.metadata

### ISSUE THREAD

**Issue by chezyann** [Kochise/docker-camisole#1]
Tried to build an image and got some errors when running :

```Traceback (most recent call last):
  File "/usr/bin/camisole", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/camisole", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/camisole", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3259, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'camisole==1.5.dev35+gf0f3daf' distribution was not found and is required by the application
Traceback (most recent call last):
  File "/usr/bin/camisole", line 10, in <module>
    from importlib.metadata import distribution
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/camisole", line 13, in <module>
    from importlib_metadata import distribution
ModuleNotFoundError: No module named 'importlib_metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/camisole", line 15, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3259, in <module>
    @_call_aside
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 3272, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 581, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 909, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 795, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'camisole==1.5.dev35+gf0f3daf' distribution was not found and is required by the application
```

Tried to edit install_root.sh to insert `python3 -m pip install -U importlib-metadata` with no luck :
```mcmurphy@8cfe75778650:/$ camisole serve
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 564, in from_name
    return next(cls.discover(name=name))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/camisole", line 33, in <module>
    sys.exit(load_entry_point('camisole==1.5.dev35+gf0f3daf', 'console_scripts', 'camisole')())
  File "/usr/bin/camisole", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 988, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/lib/python3.7/dist-packages/importlib_metadata/__init__.py", line 566, in from_name
    raise PackageNotFoundError(name)
importlib_metadata.PackageNotFoundError: No package metadata was found for camisole
```

Do you have any suggestion ?

**Comment by Kochise** [comment]
Hello, thank for opening the issue.

Sorry for the very late answer, I didn't checked before.

I did have noticed too : https://github.com/prologin/camisole/issues/60

`Camisole` not having been updated in a while, I guess we're on our own on this one.

That's mostly because my `Docker` uses the latest releases, hence backward compatibility may break.

Especially with the constantly immature `Python`, its API always on the move.

Will try to get a better look at it at some point, unless you do.

If you find the right solution, I'm all ears.

Best regards, Kochise
